<h1>Kokolitolithe, un CRUD qui vous veut du bien</h1>

<p>
    bonjour, voici une plateforme de partage de code. Regarder <a href="<?php echo $this->url(array(
				'module' => 'default',
				'controller' => 'code',
				'action' => 'liste'),
			'default', true);?>"> la liste des codes déjà existant </a> ou
    <a href="<?php echo $this->url(array(
            'module' => 'default',
            'controller' => 'code',
            'action' => 'insert'),
        'default', true) ?>"> ajouter un nouveau !</a>
</p>
